platform :ios do
  lane :beta do
    setup_ci if ENV['CI']
    match(
      type: 'appstore',
      git_url: ENV["MATCH_REPOSITORY"],
      app_identifier: ENV["APP_IDENTIFIER"],
      username: ENV["APP_STORE_CONNECT_USERNAME"],
      team_id: ENV["APP_STORE_CONNECT_TEAM_ID"]
    )
    build_app(
      project: "#{ENV['XCODE_PROJECT_PATH']}/Unity-iPhone.xcodeproj",
      scheme: "Unity-iPhone",
      export_method: "app-store",
      output_directory: "build/ios",
      output_name: "#{ENV['IOS_APP_NAME']}.ipa"
    )
    upload_to_testflight(
      api_key: {
        key_id: ENV["APPSTORE_KEY_ID"],
        issuer_id: ENV["APPSTORE_ISSUER_ID"],
        key: ENV["APPSTORE_P8"]
      },
      skip_waiting_for_build_processing: true,
      app_version: ENV["APP_VERSION"]
    )
  end
end